### PR TITLE
Bump version to 1.0.0

### PR DESCRIPTION
**Pull request by ilammy**
Actually, you know what? I’m pretty confident that this is the API that I want to use, so let’s be bold and go for stabilizing. It’s semver after all, I can always go and put out 2.0 if I find that some APIs have to be broken. It’s not like I’m going to piss off «the community» by doing this, lol.

### CODE REVIEW

**Comment by willcrichton** [comment]
I will +1 at least a new release, since the `fluid_set` macro isn't available in 0.1.0!

**Comment by willcrichton** [comment]
Please `cargo publish` when you get the chance, seems like crates.io hasn't received 1.0.0.

**Comment by ilammy** [comment]
After I merged this I did some tidying up and then moved off on a tangent to get non-optional syntax better. But somehow I don't see that happening quickly. If I don't get it working soon™ (say, by the end of this week), I think I'll hide it behind a feature flag for now and push out 1.0.0 as is.

**Comment by ilammy** [comment]
@willcrichton, so I did just that. [fluid-let 1.0.0](https://crates.io/crates/fluid-let/1.0.0) is out at crates.io now. Enjoy!

It has `fluid_set!` and utilities, but static initialization is currently hidden behind a `static-init` feature.

(Putting on my serious-maintainers-don't-break-other-people's-code-even-in-tiny-pet-projects hat.)

**Pull request merged**
